# RuboCop Default Config: https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml

AllCops:
  NewCops: disable

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/LineLength:
  Enabled: false
