name: ci

on:
  push:
    paths-ignore:
      - '**.md'
      - '.rubocop.yml'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.rubocop.yml'

jobs:
  run-tests:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-18.04]
        ruby-version: ['2.5', '2.6', '2.7']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Bundle install
      run: |
        gem install bundler && \
        bundle install --jobs 4 --retry 3

    - name: Tests
      run: bundle exec rake test
